nstmrt/slate

source/includes/_orders.md.erb

Add promocode applying section

---

source/includes/_passwords.md

https://github.com/dointeractive/instamart/pull/1398

Remove not implemented warning

---

source/includes/_addresses.md.erb

code: https://github.com/dointeractive/instamart/pull/1596

Add floor params to Address

---

source/includes/_credit_card.md
source/index.html.md

task: https://trello.com/c/OCnKreMO

Add credit card api

---

source/includes/_retailers.md.erb

task https://github.com/dointeractive/instamart/pull/1857

Add logo_background_color to retailers

---

source/includes/_credit_card.md.erb

task: https://github.com/dointeractive/instamart/pull/1878

Add payment tool

---

source/includes/_orders.md.erb

task: https://github.com/dointeractive/instamart/pull/2037

APP-106 remove promotion code

---

source/includes/_payment_tool_types.md.erb
source/index.html.md

[jira](https://instamart.atlassian.net/browse/STF-546)

Add PaymentToolTypes

---

source/includes/_addresses.md.erb

task https://github.com/dointeractive/instamart/pull/1859

Add doorphone

---

source/includes/_orders.md.erb

add orders empty

---

source/includes/_credit_card.md.erb
source/includes/_payment_tools.md.erb

https://github.com/dointeractive/instamart/pull/2393

Add credit card eligible

---

source/includes/_users.md

code https://github.com/dointeractive/instamart/pull/2469

Ad id field

---

source/includes/_credit_card.md.erb

code https://github.com/dointeractive/instamart/pull/2354

Add update card title endpount

---

source/includes/_payment_tool_types.md.erb
source/includes/_payment_tools.md.erb

[JIRA](https://instamart.atlassian.net/browse/STF-1144)

STF-1144 Add new payment method: card to courier

---

source/includes/_categories.md.erb
source/includes/_taxons.md

[JIRA](https://instamart.atlassian.net/browse/STF-1445)
[Instamart](https://github.com/dointeractive/instamart/pull/2763)

Add alt icon to categories

---

source/includes/_departments.md.erb

[JIRA](https://instamart.atlassian.net/browse/STF-1463)
[Instamart](https://github.com/dointeractive/instamart/pull/2825)

Remove taxon_id from department

---

source/includes/_promotion_codes.md.erb
source/index.html.md

https://github.com/dointeractive/instamart/pull/3088

STF 1759 api v2 for promotion codes

---

source/includes/_order_reviews.md.erb

https://github.com/dointeractive/instamart/pull/3025

STF-1523 Api V2 for order reviews

---

source/includes/_orders.md.erb

[JIRA](https://instamart.atlassian.net/browse/STF-1737)
[Instamart](https://github.com/dointeractive/instamart/pull/3081)

Add line item cancellations and replacements

---

source/includes/_categories.md.erb
source/includes/_taxons.md.erb

[STF-1832](https://instamart.atlassian.net/browse/STF-1832)

STF-1832 Api v2 add products count in taxons list

---

source/includes/_departments.md.erb
source/includes/_flags.md.erb
source/includes/_orders.md.erb
source/includes/_passwords.md.erb
source/includes/_users.md.erb

Remove duplicates v2

---

source/includes/_assembly_items.md.erb

[STF-2183](https://instamart.atlassian.net/browse/STF-2183)

STF-2183 Assembly items

---

source/includes/_orders.md.erb

[STF-2298](https://instamart.atlassian.net/browse/STF-2298)

STF-2298 Add new order's status filter for API V2

---

source/includes/_orders.md.erb
source/includes/_referrals.md.erb

[Jira Task](https://instamart.atlassian.net/browse/STF-2571)

STF-2571 Referral program API

---

source/includes/_orders.md.erb

[2644](https://instamart.atlassian.net/browse/STF-2644)

STF-2644 Rename keys

---

source/includes/_orders.md.erb

https://github.com/nstmrt/instamart/pull/4451

Update line items api

---

source/includes/_authentication.md.erb

[JIRA](https://instamart.atlassian.net/browse/STF-3364)

Add sessions user

---

source/includes/_payment_tool_types.md.erb

[STF-2933](https://instamart.atlassian.net/browse/STF-2933)

STF-2933 Use payment_methods_stores everywhere

---

source/includes/_assembly_items.md.erb

https://instamart.atlassian.net/browse/STF-3889

Added product_id && product_in_stock to assembly_items

---

source/includes/_stores.md.erb

https://instamart.atlassian.net/browse/STF-4109

STF-4109 Added next_delivery to offers controller

---

source/includes/_addresses.md.erb
source/includes/_orders.md.erb

https://instamart.atlassian.net/browse/STF-4767

STF-4767 Add description for address attributes

---

source/includes/_orders.md.erb

Docs change for [this](https://github.com/nstmrt/instamart/pull/6037)

Add driver fields to shipment

---

source/includes/_order_reviews.md.erb

https://instamart.atlassian.net/browse/STF-4788

STF-4788 Api V2 for shipment review issue

---

source/includes/_order_reviews.md.erb

https://instamart.atlassian.net/browse/STF-4789

STF-4789 Api V2 for shipment review

---

source/includes/_app_configurations.md.erb
source/index.html.md

https://instamart.atlassian.net/browse/STF-4692

STF-4692 Api V2 cloudpayments app configuration

---

source/includes/_external_partners_services.md.erb
source/index.html.md

* Added docs external partners subscriptions
[STF-5163](https://instamart.atlassian.net/browse/STF-5163)

STF-5163 external partners subscriptions list

---

source/includes/_products.md.erb

https://instamart.atlassian.net/browse/STF-4855

STF-4855 Added docs to new custom filters and discounted filters

---

source/includes/_external_partners_services.md.erb
source/index.html.md

STF-5163 add for deploy

---

source/includes/_authentication.md.erb
source/includes/_users.md.erb

https://instamart.atlassian.net/browse/STF-5251

STF-5253 Add user reg attrs for pd & promo to api/v2

---

source/includes/_external_partners_services.md.erb

[STF-5305](https://instamart.atlassian.net/browse/STF-5305)

STF-5305 add logo to service serializer
